export default defineEventHandler(async (_) => {
  return {
    code: 0,
    message: 'ok',
    data: [
      {
        id: 1,
        jobName: 'Nostar Group is recruiting waiters',
        company: 'Nostar Group',
        base: 'California, USA',
        tags: [
          'No experience required',
          'No age limit',
          'Full-time',
          'Store manager',
        ],
        salary: '$2000',
        jobContent: '',
        employer: 'Ms. Deng Recruitment Manager',
      },
      {
        id: 1,
        jobName: 'Nostar Group is recruiting waiters',
        company: 'Nostar Group',
        base: 'California, USA',
        tags: [
          'No experience required',
          'No age limit',
          'Full-time',
          'Store manager',
        ],
        salary: '$2000',
        jobContent: '',
        employer: 'Ms. Deng Recruitment Manager',
      },
      {
        id: 1,
        jobName: 'Nostar Group is recruiting waiters',
        company: 'Nostar Group',
        base: 'California, USA',
        tags: [
          'No experience required',
          'No age limit',
          'Full-time',
          'Store manager',
        ],
        salary: '$2000',
        jobContent: '',
        employer: 'Ms. Deng Recruitment Manager',
      },
      {
        id: 1,
        jobName: 'Nostar Group is recruiting waiters',
        company: 'Nostar Group',
        base: 'California, USA',
        tags: [
          'No experience required',
          'No age limit',
          'Full-time',
          'Store manager',
        ],
        salary: '$2000',
        jobContent: '',
        employer: 'Ms. Deng Recruitment Manager',
      },
      {
        id: 2,
        jobName: 'Nostar Group is recruiting waiters',
        company: 'Nostar Group',
        base: 'California, USA',
        tags: [
          'No experience required',
          'No age limit',
          'Full-time',
          'Store manager',
          'Store manager',
          'Store manager',
          'Store manager',
          'Store manager',
          'Store manager',
        ],
        salary: '$2000',
        jobContent: '',
        employer: 'Ms. Deng Recruitment Manager',
      },
    ],
  };
});
